// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopDinePortland.Models;

namespace ShopDinePortland.Solution.Migrations
{
    [DbContext(typeof(ShopDinePortlandContext))]
    [Migration("20210123004740_MoreSeedData")]
    partial class MoreSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShopDinePortland.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cuisine");

                    b.Property<string>("Name");

                    b.Property<string>("Neighborhood");

                    b.Property<string>("Service");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Cuisine = "Mediterranean",
                            Name = "Tusk",
                            Neighborhood = "East Burnside",
                            Service = "Casual Dining"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Cuisine = "Italian",
                            Name = "DeNicola's",
                            Neighborhood = "Southeast",
                            Service = "Casual Dining"
                        },
                        new
                        {
                            RestaurantId = 3,
                            Cuisine = "American",
                            Name = "PDX Sliders",
                            Neighborhood = "Sellwood",
                            Service = "Casual Dining"
                        },
                        new
                        {
                            RestaurantId = 4,
                            Cuisine = "Mexican",
                            Name = "Guero",
                            Neighborhood = "Laurelhurst",
                            Service = "Casual Dining"
                        },
                        new
                        {
                            RestaurantId = 5,
                            Cuisine = "Chinese",
                            Name = "Stretch The Noodle",
                            Neighborhood = "Downtown",
                            Service = "To-go"
                        },
                        new
                        {
                            RestaurantId = 6,
                            Cuisine = "Korean",
                            Name = "Han Oak",
                            Neighborhood = "Downtown",
                            Service = "Casual Dining"
                        },
                        new
                        {
                            RestaurantId = 7,
                            Cuisine = "Scandanavian",
                            Name = "Maurice",
                            Neighborhood = "Downtown",
                            Service = "Casual Dining"
                        });
                });

            modelBuilder.Entity("ShopDinePortland.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Neighborhood");

                    b.Property<string>("Type");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            Name = "Frances May",
                            Neighborhood = "West End",
                            Type = "Clothing"
                        },
                        new
                        {
                            ShopId = 2,
                            Name = "Machus",
                            Neighborhood = "East Burnside",
                            Type = "Clothing"
                        },
                        new
                        {
                            ShopId = 3,
                            Name = "Hay",
                            Neighborhood = "Pearl",
                            Type = "Homegoods"
                        },
                        new
                        {
                            ShopId = 4,
                            Name = "Stars Mall",
                            Neighborhood = "Sellwood",
                            Type = "Antiques"
                        },
                        new
                        {
                            ShopId = 5,
                            Name = "Beam and Anchor",
                            Neighborhood = "Northeast",
                            Type = "Homegoods"
                        },
                        new
                        {
                            ShopId = 6,
                            Name = "Spartan Shop",
                            Neighborhood = "Southeast",
                            Type = "Homegoods"
                        },
                        new
                        {
                            ShopId = 7,
                            Name = "Woonwinkel",
                            Neighborhood = "West End",
                            Type = "Homegoods"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
